### ISSUE TITLE
Add Brewery Search component

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-gatsby#6]
# Feature request

## Overview

The previous Open Brewery DB website had a simple react component which would use the API to search for a brewery. It can be imported but probably needs some revisions since it was utilizing TailwindCSS utility classes before.

## Additional context

- https://openbrewerydb.netlify.com/
- https://github.com/chrisjm/openbrewerydb-website

## Tasks

- [ ] Add Brewery Search component

## Screenshots

<img width="635" alt="Screenshot 2019-12-26 14 55 34" src="https://user-images.githubusercontent.com/96110/71492924-cab8d800-27ef-11ea-9f2f-0328576a17b4.png">

<img width="624" alt="Screenshot 2019-12-26 14 52 22" src="https://user-images.githubusercontent.com/96110/71492907-aeb53680-27ef-11ea-898a-a58b77d42e84.png">

## Implementation notes

This section will be used by the assigned developer for any additional notes.

**Comment by AndrewBarber** [comment]
I'm taking a look at this just now. 🍺

**Comment by chrisjm** [comment]
Closing this because we're moving the official website to Svelte/SvelteKit. Will create a similar ticket in the new repo, though I'll probably build it in.
